name: artificial_rains
description: "Description:\nDiscover the optimal agricultural strategies for Kuwaiti cities with our comprehensive analysis app, Kuwait Cities Analysis: Artificial Rain Advisor. Tailored specifically for Kuwait's unique climate, this app offers invaluable insights into city-specific agricultural needs, ranking, and artificial rain requirements.\n\nKey Features:\n\nCity Analysis: Access detailed analyses and rankings for Kuwaiti cities, providing crucial information on agricultural viability and artificial rain necessity.\nArtificial Rain Recommendations: Learn which cities require artificial rain to sustain agriculture and which do not, based on advanced data analysis.\nIndividual City Insights: Dive deeper into the specifics of a chosen city, receiving detailed advice for farmers and additional insights into its agricultural landscape.\nCustom Weather Evaluation: Input weather parameters to assess whether a specific set of conditions warrants artificial rain and to determine a city's eligibility for such measures.\nKuwait Cities Analysis: Artificial Rain Advisor empowers farmers, policymakers, and citizens alike with actionable intelligence for sustainable agriculture in Kuwait. Download now and harness the power of data-driven decision-making for a greener future.\n"

publish_to: "none"

version: 2.0.5

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  translator: ^1.0.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
